In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## One hot representation

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8400, 1316, 9900, 2245],
 [8400, 1316, 9900, 2131],
 [8400, 9247, 9900, 1477],
 [6097, 4996, 5588, 4936, 5962],
 [6097, 4996, 5588, 4936, 9200],
 [9001, 8400, 2803, 9900, 1374],
 [6666, 7790, 8521, 4936]]

In [16]:
sent_legth = 8

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_legth)
print(embedded_docs)

[[   0    0    0    0 8400 1316 9900 2245]
 [   0    0    0    0 8400 1316 9900 2131]
 [   0    0    0    0 8400 9247 9900 1477]
 [   0    0    0 6097 4996 5588 4936 5962]
 [   0    0    0 6097 4996 5588 4936 9200]
 [   0    0    0 9001 8400 2803 9900 1374]
 [   0    0    0    0 6666 7790 8521 4936]]


In [18]:
dim =10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_legth))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 136ms/step


array([[[-3.2057963e-02, -1.1278592e-02, -9.9879503e-03,  3.1894159e-02,
         -9.7311623e-03,  2.4464019e-03,  2.5092769e-02, -3.0151749e-02,
          3.1589415e-02,  3.8056497e-02],
        [-3.2057963e-02, -1.1278592e-02, -9.9879503e-03,  3.1894159e-02,
         -9.7311623e-03,  2.4464019e-03,  2.5092769e-02, -3.0151749e-02,
          3.1589415e-02,  3.8056497e-02],
        [-3.2057963e-02, -1.1278592e-02, -9.9879503e-03,  3.1894159e-02,
         -9.7311623e-03,  2.4464019e-03,  2.5092769e-02, -3.0151749e-02,
          3.1589415e-02,  3.8056497e-02],
        [-3.2057963e-02, -1.1278592e-02, -9.9879503e-03,  3.1894159e-02,
         -9.7311623e-03,  2.4464019e-03,  2.5092769e-02, -3.0151749e-02,
          3.1589415e-02,  3.8056497e-02],
        [ 2.4269927e-02, -1.5285026e-02, -5.9681423e-03,  4.8377108e-02,
         -2.6304960e-02, -3.9645433e-02,  1.2618527e-03,  6.6260211e-03,
         -4.7639012e-03,  2.4344210e-02],
        [-9.3098059e-03, -8.1453472e-04, -4.4131674e-02, -1.

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 8400, 1316, 9900, 2245])

In [24]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 50ms/step


array([[-0.03205796, -0.01127859, -0.00998795,  0.03189416, -0.00973116,
         0.0024464 ,  0.02509277, -0.03015175,  0.03158941,  0.0380565 ],
       [-0.03205796, -0.01127859, -0.00998795,  0.03189416, -0.00973116,
         0.0024464 ,  0.02509277, -0.03015175,  0.03158941,  0.0380565 ],
       [-0.03205796, -0.01127859, -0.00998795,  0.03189416, -0.00973116,
         0.0024464 ,  0.02509277, -0.03015175,  0.03158941,  0.0380565 ],
       [-0.03205796, -0.01127859, -0.00998795,  0.03189416, -0.00973116,
         0.0024464 ,  0.02509277, -0.03015175,  0.03158941,  0.0380565 ],
       [ 0.02426993, -0.01528503, -0.00596814,  0.04837711, -0.02630496,
        -0.03964543,  0.00126185,  0.00662602, -0.0047639 ,  0.02434421],
       [-0.00930981, -0.00081453, -0.04413167, -0.00190642,  0.0187206 ,
         0.04345557, -0.02656714, -0.00836924,  0.01313103,  0.03603086],
       [-0.01565319, -0.01760589,  0.02811748, -0.03873841,  0.04555012,
        -0.04897571, -0.01450282,  0.01827553